exclude: 'hera_cal/data/'


repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  # - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
    args: ['--unsafe']  # Only check syntax rather than try to load.
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=no']

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
