language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # create environment and install dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy=1.11.2 scipy astropy nose pip matplotlib coverage
  - source activate test-environment
  - conda install -c pkgw-forge aipy
  - pip install coveralls
  - pip install git+https://github.com/HERA-Team/pyuvdata.git
  - pip install git+https://github.com/zakiali/omnical.git
  - python setup.py install

script: nosetests hera_cal --with-coverage --cover-package=hera_cal

after_success:
  - coveralls
