name: Auto-merge Dependabot updates

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
